# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

[target.x86_64-unknown-linux-musl]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-Ctarget-feature=+crt-static"]

[alias]
xtasks = "run --manifest-path ./crates/xtasks/Cargo.toml --"
